apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdeployment
  labels:
    type: app

spec:
  replicas: 2
  selector:
    matchLabels:
       type: app
  template:
    metadata:
      name: php-pod
      labels:
        type: app
    spec:
      containers:
        - name: php-mongodb
          image: docker.io/koteswararao798988/hello:latest
          ports:
            - containerPort: 5000
              hostPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: app
